// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Printer

#ifndef _PRINTER_UI_H
#define _PRINTER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_printing_persent;
extern lv_obj_t * ui_Processing;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_print_bar1_png);    // assets/print_bar1.png
LV_IMG_DECLARE(ui_img_print_bar2_png);    // assets/print_bar2.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
